version: "3.9"
services:
  tpq-server:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_IP=redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    container_name: "tpq-redis"